[package]
name = "grid_fs"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"
authors = ["LJason <ljason@ljason.cn>"]
readme = "README.md"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[dependencies]
